name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # 기본 브랜치 이름 (master일 경우 master로 변경)
    paths:
      - 'docs/**'       # docs 폴더 내 모든 파일/하위 폴더 변경 시
  workflow_dispatch:

# GitHub Pages 배포를 위한 권한 설정
permissions:
  contents: read
  pages: write
  id-token: write

# 동시 배포 방지 설정
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # 💡 빌드할 결과물이 있는 폴더 경로 지정
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

